### ISSUE TITLE
Error: Authorization page could not be loaded on Dropbox

### ISSUE THREAD

**Issue by sorenjohanson** [Athena-Software/Owl#15]
Ref https://github.com/subdavis/Tusk/issues/339

Error is reproducible on Chrome Dev Version 81.0.4000.3 (Official Build) dev (64-bit).
In console, the same error is output as in frontend.

**Comment by sorenjohanson** [comment]
It's definitely not a wrong or missing redirect URL: when outputting the auth URL and following the link, Dropbox asks to connect to Owl. Besides, Dropbox gives an error page when using an invalid redirect URL.

I think it's an issue with newer versions of Chrome, potentially API changes.

**Comment by sorenjohanson** [comment]
Might be a permission error

https://stackoverflow.com/questions/28445656/launchwebauthflow-with-spotify-returns-authorization-page-could-not-be-loaded

**Comment by sorenjohanson** [comment]
I tried with Dropbox SDK JS; same thing, though I still relied on chrome.identity.launchWebAuthFlow. Maybe that's where the issue is.

**Comment by sorenjohanson** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=996859&q=launchWebAuthFlow&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by scrumit** [comment]
FWIW, Tusk works on Firefox 72.0.2  Build ID 20200117190643
and fails on Chrome Version 80.0.3987.87 (Official Build) (64-bit) both on Mac.

**Comment by sorenjohanson** [comment]
Chromium Team found the error - Turns out that param `reject_cors_preflight=true` in Dropbox was outdated. It should work on both master and develop now.

**Comment by rustyjarz** [comment]
I'm still getting this problem using Vavaldi, details below. 

Vivaldi | 2.11.1811.44 (Stable channel) (64-bit)
-- | --
Revision | cfb29c8f57474ba1f117689089c9128efd652d3f
OS | Windows 10 OS Version 1909 (Build 18363.657)
JavaScript | V8 8.0.426.25

**Comment by sorenjohanson** [comment]
@rustyjarz Thanks for the info, I'll try and look into it this week.

**Comment by sorenjohanson** [comment]
I just tested it and I can reproduce it on Vivaldi Stable:

Vivaldi | 2.11.1811.52 (Stable channel) (64-bit)
-- | --
Revision | 88f335a58f46e6372fa8f4d540ccac8380af31a6
OS | Linux
JavaScript | V8 8.0.426.30

Also repro case on Chrome Stable: 

Google Chrome | 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | Linux
JavaScript | V8 8.0.426.30

However, Dropbox works on Chrome Unstable:

Google Chrome | 83.0.4100.3 (Official Build) dev (64-bit)
-- | --
Revision | 88ec42d480fd1d68b575356ad83c03be2b314957-refs/branch-heads/4100@{#6}
OS | Linux
JavaScript | V8 8.3.103

**Comment by sorenjohanson** [comment]
Also works on Firefox 74 (latest stable)

**Comment by sorenjohanson** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1049565#c2

Now it's actually a bug in Chromium :D
It has been fixed in Chrome 82, hence it works on unstable. However, Chrome 80 just hit stable release 4 days ago, so I suspect it'll be some time until they update stable to 82/83 and Vivaldi gets the update.

I'll pin this issue again so people are aware.
@rustyjarz

**Comment by scrumit** [comment]
Wonderful. So glad chromium people picked this up. Looking forward to using Owl.

**Comment by FRYYYYYY** [comment]
Also working for me within Edge, Version 81.0.416.64.

**Comment by sorenjohanson** [comment]
Still seeing this error pop up in Chrome 83 on macOS Catalina 10.15.3. I'm gonna double check Chrome Dev.

**Comment by sorenjohanson** [comment]
Nevermind.

If a proper Redirect URI is not set in Dropbox Developer App Console, then Chrome simply drops the OAuth Request and displays "Authorization page could not be loaded". Manually following the URL shows that the bad Redirect URI is the cause.

So it finally works with Chrome 83! I'll close this issue.
