### ISSUE TITLE
Build on Mac has errors

### ISSUE THREAD

**Issue by scrumit** [Athena-Software/Owl#24]
## Bug report
I followed the instructions and got an error on "yarn install"
### Steps to reproduce - current behaviour
Clone owl repo
go to Owl directory
find you haven't got yarn and install with brew
type "yarn install"

### What is the expected behaviour

That I don't get an error
#### Additional remarks
Here's the output:

yarn install
yarn install v1.22.4
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning keeweb > time-grunt@2.0.0: Deprecated because Grunt is practically unmaintained. Move on to something better. This package will continue to work with Grunt v1, but it will not receive any updates.
warning keeweb > node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning keeweb > node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning keeweb > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning keeweb > webpack > watchpack > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning keeweb > webpack-dev-server > chokidar > fsevents@1.2.12: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning keeweb > grunt-contrib-compress > iltorb@2.4.5: The zlib module provides APIs for brotli compression/decompression starting with Node.js v10.16.0, please use it over iltorb
warning keeweb > webpack > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning keeweb > webpack > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning keeweb > babel-cli > chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning keeweb > babel-cli > chokidar > fsevents@1.2.12: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning keeweb > babel-cli > babel-polyfill > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning keeweb > babel-cli > babel-register > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning keeweb > babel-cli > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
error An unexpected error occurred: "https://github.com/keeweb/grunt-inline-alt: connect ETIMEDOUT 140.82.118.3:443".
info If you think this is a bug, please open a bug report with the information provided in "/Users/mel/Owl/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
mel@Mels-MBP Owl % 

#### Environment 

**Operating System:**
Mac OS Catalina 10.15.5 beta (19F62f)
**Browser vendor and version:**
Mozilla Firefox 75.0 (64-bit)
**Storage Provider:**
Not got that far but normally use Dropbox. Can try most others

**Comment by ekarbe** [comment]
Looks like a network error. Did you try running `yarn install`again?

Not reproducable on master branch with:
- yarn 1.22.4
- Mac OS Catalina 10.15.3

@CER10TY will test again

**Comment by sorenjohanson** [comment]
I'll repro again on Thursday, @scrumit please let me know if this issue persists till then.

**Comment by ekarbe** [comment]
Bump @CER10TY

**Comment by sorenjohanson** [comment]
Finally had time to check this out on my Mac. Both `yarn build` and `yarn install` work without any issues using macOS Catalina 10.15.3, though it is inconvenient at best to try and build this on a Mac due to the hassle with brew, node symlinks etc. 

As I haven't heard anything in a while, I'll close this issue for now; if there's an issue in the future, please get back to us.
