### ISSUE TITLE
Can't use Dropbox as cloud storage on Firefox

### ISSUE THREAD

**Issue by askuri** [Athena-Software/Owl#27]
### Steps to reproduce - current behaviour
1. Add a new database
2. Cloud storage setup
3. Dropbox
4. Message pops up: "This app has reached its user limit. Contact the app developer and ask them to use the Dropbox API App Console to increase their app's user limit."

### What is the expected behaviour
Logging in on Dropbox and granting permission

#### Environment 
* OS: Kubuntu 19.10
* Firefox 76, addon installed from the firefox store
* Storage: dropbox

I really appreciate someone is resurrecting Tusk again! Looking forward to use it and install it on my girlfriend's laptop on Chrome.

**Comment by sorenjohanson** [comment]
Hi,

yeah, the OAuth2 app currently has a user limit in place. However, I've raised it to 500 now. Please try again and let me know!

(Also applied the app for production so the user cap is gone, but this is going to take ~1 month)

**Comment by askuri** [comment]
Tried it again and works, thanks!
