### ISSUE TITLE
Implement Privacy Policy

### ISSUE THREAD

**Issue by sorenjohanson** [Athena-Software/Owl#28]
Chrome Web Store requires a detailed privacy policy to be up on https://athena-software.github.io/Owl/ including details of why every permission is necessary etc.

More specifically:

> Your privacy policy and in-product privacy notifications must thoroughly disclose the manner in which your application accesses, uses, stores, or shares Google user data. Your use of Google user data must be limited to the practices explicitly disclosed in your published privacy policy.

**Comment by CER10TY** [comment]
slack test

**Comment by sorenjohanson** [comment]
A first draft of the privacy policy has been released:

https://athena-software.github.io/Owl/privacy-policy.html#privacy-policy

**Comment by sorenjohanson** [comment]
Privacy Policy has been reviewed and accepted by Google; ready for release.
