### ISSUE TITLE
Can't make Owl to work with Webdav on Firefox

### ISSUE THREAD

**Issue by Flore-mozfr** [Athena-Software/Owl#30]
Hello,

I've een using Tusk for quite long now and I'm trying to switch to Owl, but I'm encountering some issues on Firefox.
My keepass file is hosted on a nextcloud instance, So I use webdav, put the same exact URL than in Tusk (which is still installed), username and password and nothing happens as I click on the button "ADD SERVER". No error, nothing just as if I did not click. Of course, I can not scan the directory, because nothing happened.
But it does check something: if the URL is not correctly formatted (no /) there's an error message, but as soon as it matches the regular expression : nothing happens.

So I decided to use a shared link, created a the shared link, put the correct filename (with extension), so it takes the filename. But when I try to open it (put my password, or absolutely anything, doesn't matter), it says "This is not a valid KeyPass file - File signature is not correct". Of course, it is a valid KeePass file, I use it everywhere (KeePassXC, Keepass2Droid, Tusk...).

So, I have no idea what the issue is, but I am willing to help debug it .

Owl Version: 2020.4.28.1
Nextcloud Version: 18.04
Firefox Nightly: 78.0a1 (2020-05-27) (64 bits)

**Comment by sorenjohanson** [comment]
Hi,

can you attach a screenshot of your WebDAV config in both Tusk and Owl please?
And does it show you any error in the development console (F12) when you click Add Server?

Thanks for reporting the issue.

**Comment by sorenjohanson** [comment]
And just to clarify no-repro: Tested with OpenDrive WebDAV on Firefox Stable 76.0.1, no digest auth. That setup works on my side, but I don't have a Nextcloud instance to test it with that.

**Comment by Flore-mozfr** [comment]
Hello,

Here are the screenshots 
1. Config in Owl
![Capture d’écran 2020-05-28 à 21 00 19](https://user-images.githubusercontent.com/6987429/83183817-c7bc6d80-a128-11ea-92a5-6259cf11a0a1.png)
2. Config in Tusk (with Console)
![Capture d’écran 2020-05-28 à 21 00 31](https://user-images.githubusercontent.com/6987429/83183824-cab75e00-a128-11ea-922f-be6522d3312d.png)
3. Config in Owl (with network : error 401)
![Capture d’écran 2020-05-28 à 21 10 07](https://user-images.githubusercontent.com/6987429/83183841-cf7c1200-a128-11ea-8eba-0cbf986e670b.png)
4. Config in Tusk (Network : works sends 207)
![Capture d’écran 2020-05-28 à 21 10 49](https://user-images.githubusercontent.com/6987429/83183846-d145d580-a128-11ea-8c4e-efb379e49e92.png)

I redacted the servername and login because I may be paranoid. But to be absolutely extra sure the values are identical, I copied the values in both tabs from the same source (first in Tusk, then in Owl, next value)

**Comment by sorenjohanson** [comment]
Are you super super super positive that the credentials are correct? Error 401 tells me it's Unauthorized, ie. the wrong credentials have been given. Unfortunately there's no way to show the password in plaintext to verify easily, but right now this sounds like a typo in the password to me.

Alternative: Did you switch to Digest Auth recently? This may be far fetched, since Tusk does not support WebDAV Digest Auth at all (afaik), but worth checking if you can connect by ticking the Digest Auth box.

**Comment by Flore-mozfr** [comment]
OK, I tested on a fresh nightly install / new profile and both Tusk and Owl work.
I have no idea what prevents owl from working in my regular Nightly profile when it works in a fresh profile (although Tusk works). Maybe an addon...

Very weird. If I find out, I'll let you know...

Sorry to have bothered you.

**Comment by sorenjohanson** [comment]
Glad you could resolve the issue at least!

**Comment by Flore-mozfr** [comment]
I disabled all my extensions and refreshed my nightly profile. It did not work because Sync added all my extensions (deactivated, but still they were there).
So I refreshed again and logged out from Sync, added Owl from AMO and finally it worked.
So, one of my addons messes up with Owl authetification, while it does not with Tusk.

File it under weird bugs...
